Traceback (most recent call last):
  File "/Users/guy/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/guy/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/guy/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/guy/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/guy/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/guy/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/guy/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/guy/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
bike_share_data = (
    pd
    .read_csv(
        'https://archive.ics.uci.edu/ml/machine-learning-databases/00560/SeoulBikeData.csv', 
        encoding='latin1'
    )
)
bike_share_data
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mConnectionResetError[0m                      Traceback (most recent call last)
[0;32m<ipython-input-2-7695f8b7dd5e>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m bike_share_data = (
[0;32m----> 2[0;31m     [0mpd[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m     .read_csv(
[1;32m      4[0m         [0;34m'https://archive.ics.uci.edu/ml/machine-learning-databases/00560/SeoulBikeData.csv'[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m         [0mencoding[0m[0;34m=[0m[0;34m'latin1'[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py[0m in [0;36mread_csv[0;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)[0m
[1;32m    608[0m     [0mkwds[0m[0;34m.[0m[0mupdate[0m[0;34m([0m[0mkwds_defaults[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    609[0m [0;34m[0m[0m
[0;32m--> 610[0;31m     [0;32mreturn[0m [0m_read[0m[0;34m([0m[0mfilepath_or_buffer[0m[0;34m,[0m [0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    611[0m [0;34m[0m[0m
[1;32m    612[0m [0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py[0m in [0;36m_read[0;34m(filepath_or_buffer, kwds)[0m
[1;32m    460[0m [0;34m[0m[0m
[1;32m    461[0m     [0;31m# Create the parser.[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 462[0;31m     [0mparser[0m [0;34m=[0m [0mTextFileReader[0m[0;34m([0m[0mfilepath_or_buffer[0m[0;34m,[0m [0;34m**[0m[0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    463[0m [0;34m[0m[0m
[1;32m    464[0m     [0;32mif[0m [0mchunksize[0m [0;32mor[0m [0miterator[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py[0m in [0;36m__init__[0;34m(self, f, engine, **kwds)[0m
[1;32m    817[0m             [0mself[0m[0;34m.[0m[0moptions[0m[0;34m[[0m[0;34m"has_index_names"[0m[0;34m][0m [0;34m=[0m [0mkwds[0m[0;34m[[0m[0;34m"has_index_names"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    818[0m [0;34m[0m[0m
[0;32m--> 819[0;31m         [0mself[0m[0;34m.[0m[0m_engine[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_make_engine[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mengine[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    820[0m [0;34m[0m[0m
[1;32m    821[0m     [0;32mdef[0m [0mclose[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py[0m in [0;36m_make_engine[0;34m(self, engine)[0m
[1;32m   1048[0m             )
[1;32m   1049[0m         [0;31m# error: Too many arguments for "ParserBase"[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1050[0;31m         [0;32mreturn[0m [0mmapping[0m[0;34m[[0m[0mengine[0m[0;34m][0m[0;34m([0m[0mself[0m[0;34m.[0m[0mf[0m[0;34m,[0m [0;34m**[0m[0mself[0m[0;34m.[0m[0moptions[0m[0;34m)[0m  [0;31m# type: ignore[call-arg][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1051[0m [0;34m[0m[0m
[1;32m   1052[0m     [0;32mdef[0m [0m_failover_to_python[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py[0m in [0;36m__init__[0;34m(self, src, **kwds)[0m
[1;32m   1865[0m [0;34m[0m[0m
[1;32m   1866[0m         [0;31m# open handles[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1867[0;31m         [0mself[0m[0;34m.[0m[0m_open_handles[0m[0;34m([0m[0msrc[0m[0;34m,[0m [0mkwds[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1868[0m         [0;32massert[0m [0mself[0m[0;34m.[0m[0mhandles[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1869[0m         [0;32mfor[0m [0mkey[0m [0;32min[0m [0;34m([0m[0;34m"storage_options"[0m[0;34m,[0m [0;34m"encoding"[0m[0;34m,[0m [0;34m"memory_map"[0m[0;34m,[0m [0;34m"compression"[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py[0m in [0;36m_open_handles[0;34m(self, src, kwds)[0m
[1;32m   1360[0m         [0mLet[0m [0mthe[0m [0mreaders[0m [0mopen[0m [0mIOHanldes[0m [0mafter[0m [0mthey[0m [0mare[0m [0mdone[0m [0;32mwith[0m [0mtheir[0m [0mpotential[0m [0mraises[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1361[0m         """
[0;32m-> 1362[0;31m         self.handles = get_handle(
[0m[1;32m   1363[0m             [0msrc[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1364[0m             [0;34m"r"[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/common.py[0m in [0;36mget_handle[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)[0m
[1;32m    556[0m [0;34m[0m[0m
[1;32m    557[0m     [0;31m# open URLs[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 558[0;31m     ioargs = _get_filepath_or_buffer(
[0m[1;32m    559[0m         [0mpath_or_buf[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    560[0m         [0mencoding[0m[0;34m=[0m[0mencoding[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.8/site-packages/pandas/io/common.py[0m in [0;36m_get_filepath_or_buffer[0;34m(filepath_or_buffer, encoding, compression, mode, storage_options)[0m
[1;32m    292[0m             [0;31m# Override compression based on Content-Encoding header[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    293[0m             [0mcompression[0m [0;34m=[0m [0;34m{[0m[0;34m"method"[0m[0;34m:[0m [0;34m"gzip"[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 294[0;31m         [0mreader[0m [0;34m=[0m [0mBytesIO[0m[0;34m([0m[0mreq[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    295[0m         [0mreq[0m[0;34m.[0m[0mclose[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    296[0m         return IOArgs(

[0;32m~/opt/anaconda3/lib/python3.8/http/client.py[0m in [0;36mread[0;34m(self, amt)[0m
[1;32m    469[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    470[0m                 [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 471[0;31m                     [0ms[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_safe_read[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mlength[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    472[0m                 [0;32mexcept[0m [0mIncompleteRead[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    473[0m                     [0mself[0m[0;34m.[0m[0m_close_conn[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.8/http/client.py[0m in [0;36m_safe_read[0;34m(self, amt)[0m
[1;32m    610[0m         [0mIncompleteRead[0m [0mexception[0m [0mcan[0m [0mbe[0m [0mused[0m [0mto[0m [0mdetect[0m [0mthe[0m [0mproblem[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m    611[0m         """
[0;32m--> 612[0;31m         [0mdata[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mfp[0m[0;34m.[0m[0mread[0m[0;34m([0m[0mamt[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    613[0m         [0;32mif[0m [0mlen[0m[0;34m([0m[0mdata[0m[0;34m)[0m [0;34m<[0m [0mamt[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    614[0m             [0;32mraise[0m [0mIncompleteRead[0m[0;34m([0m[0mdata[0m[0;34m,[0m [0mamt[0m[0;34m-[0m[0mlen[0m[0;34m([0m[0mdata[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.8/socket.py[0m in [0;36mreadinto[0;34m(self, b)[0m
[1;32m    667[0m         [0;32mwhile[0m [0;32mTrue[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    668[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 669[0;31m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_sock[0m[0;34m.[0m[0mrecv_into[0m[0;34m([0m[0mb[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    670[0m             [0;32mexcept[0m [0mtimeout[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    671[0m                 [0mself[0m[0;34m.[0m[0m_timeout_occurred[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.8/ssl.py[0m in [0;36mrecv_into[0;34m(self, buffer, nbytes, flags)[0m
[1;32m   1239[0m                   [0;34m"non-zero flags not allowed in calls to recv_into() on %s"[0m [0;34m%[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1240[0m                   self.__class__)
[0;32m-> 1241[0;31m             [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mread[0m[0;34m([0m[0mnbytes[0m[0;34m,[0m [0mbuffer[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1242[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1243[0m             [0;32mreturn[0m [0msuper[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mrecv_into[0m[0;34m([0m[0mbuffer[0m[0;34m,[0m [0mnbytes[0m[0;34m,[0m [0mflags[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.8/ssl.py[0m in [0;36mread[0;34m(self, len, buffer)[0m
[1;32m   1097[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1098[0m             [0;32mif[0m [0mbuffer[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1099[0;31m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_sslobj[0m[0;34m.[0m[0mread[0m[0;34m([0m[0mlen[0m[0;34m,[0m [0mbuffer[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1100[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1101[0m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_sslobj[0m[0;34m.[0m[0mread[0m[0;34m([0m[0mlen[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mConnectionResetError[0m: [Errno 54] Connection reset by peer
ConnectionResetError: [Errno 54] Connection reset by peer

